apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer               #to make it an external service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000              # between 30000 - 32767  - port for external ip address (that we put into browser)